In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder

C:\Users\ASUS\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
#Data for Recommendation
DataForRecommendation = pd.read_excel("Champo.xlsx", sheet_name = 'Data for Recommendation')

In [4]:
DataForRecommendation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 44 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer      20 non-null     object
 1   Hand Tufted   20 non-null     int64
 2   Double Wowen  20 non-null     int64
 3   Durry         20 non-null     int64
 4   Double Back   20 non-null     int64
 5   Knotted       20 non-null     int64
 6   Jacquared     20 non-null     int64
 7   Handloom      20 non-null     int64
 8   Other         20 non-null     int64
 9   Rectangle     20 non-null     int64
 10  Square        20 non-null     int64
 11  Round         20 non-null     int64
 12  Purple        20 non-null     int64
 13  Gray          20 non-null     int64
 14  Navy          20 non-null     int64
 15  PINK          20 non-null     int64
 16  BLUE          20 non-null     int64
 17  BLUSH PINK    20 non-null     int64
 18  NEUTRAL       20 non-null     int64
 19  TAN           20 non-null     int64
 20  NAVY          20 non-null     int64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Customer .1   20 non-null     object
 24  H-2           20 non-null     int64
 25  P-5           20 non-null     int64
 26  M-1           20 non-null     int64
 27  A-9           20 non-null     int64
 28  C-2           20 non-null     int64
 29  JL            20 non-null     int64
 30  N-1           20 non-null     int64
 31  T-5           20 non-null     int64
 32  C-1           20 non-null     int64
 33  T-2           20 non-null     int64
 34  I-2           20 non-null     int64
 35  PD            20 non-null     int64
 36  L-5           20 non-null     int64
 37  M-2           20 non-null     int64
 38  RC            20 non-null     int64
 39  P-4           20 non-null     int64
 40  T-4           20 non-null     int64
 41  PC            20 non-null     int64
 42  A-11          20 non-null     int64
 43  CC            20 non-null     int64
dtypes: float64(2), int64(40), object(2)
memory usage: 7.0+ KB

In [5]:
DataForRecommendation.head()

,Customer,Hand Tufted,Double Wowen,Durry,Double Back,Knotted,Jacquared,Handloom,Other,Rectangle,...,I-2,PD,L-5,M-2,RC,P-4,T-4,PC,A-11,CC
0,H-2,26612,3000,139618,0,0,550,3673,9753,132756,...,3657,0,0,4418,1130,133,3667,1294,0,5021
1,P-5,2352,5340,25997,4691,9502,353,138,0,47951,...,1126,191,0,168,332,56,0,0,0,0
2,M-1,2697,3085,412,5439,3626,60,1085,245,16619,...,978,9950,25840,1869,527,12900,1560,0,1021,4
3,A-9,11716,2116,3585,175,617,714,0,0,18923,...,410,414,0,0,224,0,0,0,0,3
4,C-2,3816,14314,37042,0,0,0,0,0,55172,...,56,388,0,0,350,0,0,0,0,0

In [6]:
DataForRecommendation.describe()

,Hand Tufted,Double Wowen,Durry,Double Back,Knotted,Jacquared,Handloom,Other,Rectangle,Square,...,I-2,PD,L-5,M-2,RC,P-4,T-4,PC,A-11,CC
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,7142.800000,1918.100000,15702.700000,821.750000,800.900000,172.200000,412.35000,691.500000,24883.900000,18.400000,...,800.700000,1182.600000,3098.200000,743.50000,321.800000,2049.700000,596.700000,137.650000,246.60000,568.250000
std,13906.994638,3383.143772,31574.440784,1668.514621,2206.710076,235.502509,870.10981,2275.076945,32143.788964,70.174519,...,1735.005721,3217.846442,7934.981389,1675.63457,674.340973,4600.452027,1474.918378,396.324731,648.69873,1528.331559
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1293.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,1253.000000,0.000000,498.250000,0.000000,0.000000,0.000000,0.00000,0.000000,5036.500000,0.000000,...,74.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,3600.500000,276.000000,2727.000000,1.500000,0.000000,25.000000,15.00000,0.000000,13879.500000,0.000000,...,152.000000,13.000000,0.000000,0.00000,53.000000,25.000000,0.000000,0.000000,0.00000,3.500000
75%,4568.750000,2656.500000,16135.000000,411.000000,404.250000,378.750000,408.75000,38.750000,29921.750000,1.250000,...,539.000000,316.000000,0.000000,465.00000,336.500000,838.500000,240.000000,0.250000,0.00000,201.500000
max,60685.000000,14314.000000,139618.000000,5439.000000,9502.000000,714.000000,3673.00000,9753.000000,132756.000000,315.000000,...,7291.000000,11140.000000,25840.000000,6361.00000,2931.000000,16653.000000,5677.000000,1294.000000,2466.00000,5023.000000

In [7]:
DataForRecommendation.columns

Index(['Customer ', 'Hand Tufted', 'Double Wowen', 'Durry', 'Double Back',
       'Knotted', 'Jacquared', 'Handloom', 'Other', 'Rectangle', 'Square',
       'Round', 'Purple', 'Gray', 'Navy', 'PINK', 'BLUE', 'BLUSH PINK',
       'NEUTRAL', 'TAN', 'NAVY', 'Unnamed: 21', 'Unnamed: 22', 'Customer .1',
       'H-2', 'P-5', 'M-1', 'A-9', 'C-2', 'JL', 'N-1', 'T-5', 'C-1', 'T-2',
       'I-2', 'PD', 'L-5', 'M-2', 'RC', 'P-4', 'T-4', 'PC', 'A-11', 'CC'],
      dtype='object')

In [34]:
rec_data = DataForRecommendation.drop(['Unnamed: 21', 'Unnamed: 22', 'Customer .1',
       'H-2', 'P-5', 'M-1', 'A-9', 'C-2', 'JL', 'N-1', 'T-5', 'C-1', 'T-2',
       'I-2', 'PD', 'L-5', 'M-2', 'RC', 'P-4', 'T-4', 'PC', 'A-11', 'CC'], axis = 'columns')

In [45]:
rec_data

,Customer,Hand Tufted,Double Wowen,Durry,Double Back,Knotted,Jacquared,Handloom,Other,Rectangle,...,Round,Purple,Gray,Navy,PINK,BLUE,BLUSH PINK,NEUTRAL,TAN,NAVY
0,H-2,26612,3000,139618,0,0,550,3673,9753,132756,...,50540,0,0,16235,0,15537,0,0,0,16235
1,P-5,2352,5340,25997,4691,9502,353,138,0,47951,...,107,0,1863,0,0,6218,0,0,0,0
2,M-1,2697,3085,412,5439,3626,60,1085,245,16619,...,0,0,1216,53,138,69,0,0,0,53
3,A-9,11716,2116,3585,175,617,714,0,0,18923,...,0,0,273,1843,552,705,0,1832,0,1843
4,C-2,3816,14314,37042,0,0,0,0,0,55172,...,0,0,2007,1601,0,0,0,0,0,1601
5,JL,3544,5110,5310,3575,1026,231,0,65,18767,...,94,55,808,0,316,1574,0,0,0,0
6,N-1,60685,0,12203,0,0,0,0,0,70692,...,2196,0,0,8080,0,14418,0,0,0,8080
7,T-5,5302,2542,34651,262,0,100,110,0,42167,...,800,0,5574,2246,875,2709,250,0,0,2246
8,C-1,4176,220,288,0,453,0,0,0,5041,...,93,0,24,52,0,38,0,52,0,52
9,T-2,2636,762,299,1242,0,0,395,134,4915,...,540,0,102,0,0,0,0,0,0,0
10,I-2,3657,1126,978,410,56,456,788,30,7291,...,210,94,260,80,82,336,0,80,0,80
11,PD,0,191,9950,414,388,50,133,20,11140,...,0,0,1068,0,0,292,0,0,0,0
12,L-5,0,0,25840,0,0,0,0,0,25840,...,0,0,5142,0,0,5142,0,0,0,0
13,M-2,4418,168,1869,0,0,471,0,0,6361,...,463,0,310,0,263,547,0,0,0,0
14,RC,1130,332,527,224,350,459,0,0,2931,...,91,0,236,50,56,0,0,0,0,50
15,P-4,133,56,12900,0,0,0,0,3564,16653,...,0,0,2955,50,56,4577,0,0,0,50
16,T-4,3667,0,1560,0,0,0,450,0,5677,...,0,0,300,0,60,220,0,0,0,0
17,PC,1294,0,0,0,0,0,0,0,1293,...,0,0,124,0,0,0,0,0,41,0
18,A-11,0,0,1021,0,0,0,1445,0,2466,...,0,0,0,0,0,0,0,0,0,0
19,CC,5021,0,4,3,0,0,30,19,5023,...,53,0,299,371,1,169,0,0,0,371

In [10]:
from sklearn.preprocessing import MinMaxScaler

# Normalize the data
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(rec_data.iloc[:, 1:])

In [11]:
data_scaled

array([[4.38526819e-01, 2.09585022e-01, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 7.70308123e-01, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.87575183e-02, 3.73061339e-01, 1.86200920e-01, 8.62474720e-01,
        1.00000000e+00, 4.94397759e-01, 3.75714675e-02, 0.00000000e+00,
        3.54913550e-01, 1.00000000e+00, 2.11713494e-03, 0.00000000e+00,
        3.34230355e-01, 0.00000000e+00, 0.00000000e+00, 4.00205960e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.44426135e-02, 2.15523264e-01, 2.95090891e-03, 1.00000000e+00,
        3.81603873e-01, 8.40336134e-02, 2.95398857e-01, 2.51204758e-02,
        1.16580331e-01, 9.52380952e-02, 0.00000000e+00, 0.00000000e+00,
        2.18155723e-01, 3.26455189e-03, 1.57714286e-01, 4.44101178e-03,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.26455189e-03],
       [1.93062536e-01, 1.47827302e-01, 2.56772049e-02, 3.21750322e-02,
        6.49336982e-02, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.34106174e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.89773950e-02, 1.13520172e-01, 6.30857143e-01, 4.53755551e-02,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.13520172e-01],
       [6.28820961e-02, 1.00000000e+00, 2.65309631e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.09841552e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.60064586e-01, 9.86141053e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.86141053e-02],
       [5.83999341e-02, 3.56993154e-01, 3.80323454e-02, 6.57289943e-01,
        1.07977268e-01, 3.23529412e-01, 0.00000000e+00, 6.66461602e-03,
        1.32919529e-01, 0.00000000e+00, 1.85991294e-03, 5.85106383e-01,
        1.44958737e-01, 0.00000000e+00, 3.61142857e-01, 1.01306559e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 8.74027704e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.27897583e-01, 0.00000000e+00, 4.34507321e-02, 0.00000000e+00,
        0.00000000e+00, 4.97690176e-01, 0.00000000e+00, 9.27978374e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.97690176e-01],
       [8.73692016e-02, 1.77588375e-01, 2.48184332e-01, 4.81706196e-02,
        0.00000000e+00, 1.40056022e-01, 2.99482712e-02, 0.00000000e+00,
        3.10916380e-01, 0.00000000e+00, 1.58290463e-02, 0.00000000e+00,
        1.00000000e+00, 1.38343086e-01, 1.00000000e+00, 1.74357984e-01,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.38343086e-01],
       [6.88143693e-02, 1.53695683e-02, 2.06277128e-03, 0.00000000e+00,
        4.76741739e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.85099229e-02, 6.34920635e-03, 1.84012663e-03, 0.00000000e+00,
        4.30570506e-03, 3.20295658e-03, 0.00000000e+00, 2.44577460e-03,
        0.00000000e+00, 2.83842795e-02, 0.00000000e+00, 3.20295658e-03],
       [4.34374228e-02, 5.32345955e-02, 2.14155768e-03, 2.28350800e-01,
        0.00000000e+00, 0.00000000e+00, 1.07541519e-01, 1.37393622e-02,
        2.75514784e-02, 4.12698413e-02, 1.06846063e-02, 0.00000000e+00,
        1.82992465e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.02620087e-02, 7.86642448e-02, 7.00482746e-03, 7.53815040e-02,
        5.89349611e-03, 6.38655462e-01, 2.14538524e-01, 3.07597662e-03,
        4.56250048e-02, 0.00000000e+00, 4.15512465e-03, 1.00000000e+00,
        4.66451381e-02, 4.92762550e-03, 9.37142857e-02, 2.16257965e-02,
        0.00000000e+00, 4.36681223e-02, 0.00000000e+00, 4.92762550e-03],
       [0.00000000e+00, 1.33435797e-02, 7.12658826e-02, 7.61169333e-02,
        4.08335087e-02, 7.00280112e-02, 3.62101824e-02, 2.05065108e-03,
        7.49032047e-02, 1.90476190e-02, 0.00000000e+00, 0.00000000e+00,
        1.91603875e-01, 0.00000000e+00, 0.00000000e+00, 1.87938469e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.85076423e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.86721739e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.22497309e-01, 0.00000000e+00, 0.00000000e+00, 3.30951921e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.28021752e-02, 1.17367612e-02, 1.33865261e-02, 0.00000000e+00,
        0.00000000e+00, 6.59663866e-01, 0.00000000e+00, 0.00000000e+00,
        3.85507709e-02, 0.00000000e+00, 9.16106055e-03, 0.00000000e+00,
        5.56153570e-02, 0.00000000e+00, 3.00571429e-01, 3.52062818e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.86207465e-02, 2.31940757e-02, 3.77458494e-03, 4.11840412e-02,
        3.68343507e-02, 6.42857143e-01, 0.00000000e+00, 0.00000000e+00,
        1.24597796e-02, 0.00000000e+00, 1.80055402e-03, 0.00000000e+00,
        4.23394331e-02, 3.07976594e-03, 6.40000000e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.07976594e-03],
       [2.19164538e-03, 3.91225374e-03, 9.23949634e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.65426023e-01,
        1.16838958e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.30139935e-01, 3.07976594e-03, 6.40000000e-02, 2.94587115e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.07976594e-03],
       [6.04267941e-02, 0.00000000e+00, 1.11733444e-02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.22515655e-01, 0.00000000e+00,
        3.33477861e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.38213132e-02, 0.00000000e+00, 6.85714286e-02, 1.41597477e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.13232265e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.17460317e-03, 0.00000000e+00, 0.00000000e+00,
        2.22461428e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 7.31281067e-03, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 3.93411380e-01, 0.00000000e+00,
        8.92266265e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.27387328e-02, 0.00000000e+00, 2.86496011e-05, 5.51571980e-04,
        0.00000000e+00, 0.00000000e+00, 8.16771032e-03, 1.94811853e-03,
        2.83730023e-02, 3.17460317e-03, 1.04867432e-03, 0.00000000e+00,
        5.36419089e-02, 2.28518633e-02, 1.14285714e-03, 1.08772607e-02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.28518633e-02]])

In [46]:
# Create a user-item matrix
customers = rec_data["Customer "]

In [47]:
carpet_attributes = rec_data.columns[1:]

In [48]:
carpet_attributes

Index(['Hand Tufted', 'Double Wowen', 'Durry', 'Double Back', 'Knotted',
       'Jacquared', 'Handloom', 'Other', 'Rectangle', 'Square', 'Round',
       'Purple', 'Gray', 'Navy', 'PINK', 'BLUE', 'BLUSH PINK', 'NEUTRAL',
       'TAN', 'NAVY'],
      dtype='object')

In [49]:
user_item_matrix = pd.DataFrame(data_scaled, columns=carpet_attributes, index=customers)

In [50]:
import tensorflow as tf

# Set the hyperparameters
num_hidden1 = 50
num_hidden2 = 10
num_epochs = 100
learning_rate = 0.001

In [51]:
# Define the model architecture
input_layer = tf.keras.layers.Input(shape=(user_item_matrix.shape[1],))
hidden1 = tf.keras.layers.Dense(num_hidden1, activation='relu')(input_layer)
hidden2 = tf.keras.layers.Dense(num_hidden2, activation='relu')(hidden1)
output_layer = tf.keras.layers.Dense(user_item_matrix.shape[1], activation='sigmoid')(hidden2)

In [52]:
# Create the model
model = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

In [54]:
# Compile the model
model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(lr=learning_rate))

WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.

In [55]:
# Train the model
history = model.fit(user_item_matrix, user_item_matrix, epochs=num_epochs, verbose=0)

In [91]:
# Make predictions for a particular customer
customer_name = 'H-2'
customer_data = rec_data.loc[rec_data['Customer '] == customer_name].iloc[:, 1:]
customer_predictions = model.predict(customer_data)

1/1 [==============================] - 0s 56ms/step

In [92]:
# Get the recommended carpet attributes
recommendations = carpet_attributes[customer_predictions[0].argsort()[::-1]]

In [93]:
# Create a DataFrame with two columns: Customer & Attribute 
df_recommendations = pd.DataFrame({'Attribute': recommendations, 'Customer': customer_name})

# Print the DataFrame
print(df_recommendations)

       Attribute Customer
0           NAVY      H-2
1      Rectangle      H-2
2          Durry      H-2
3    Hand Tufted      H-2
4           BLUE      H-2
5           PINK      H-2
6           Navy      H-2
7           Gray      H-2
8         Purple      H-2
9          Round      H-2
10           TAN      H-2
11    BLUSH PINK      H-2
12         Other      H-2
13      Handloom      H-2
14     Jacquared      H-2
15       Knotted      H-2
16   Double Back      H-2
17       NEUTRAL      H-2
18  Double Wowen      H-2
19        Square      H-2

In [60]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(rec_data, test_size=0.2, random_state=30)
# Create user-item matrices for the training and test data
train_customers = train_data['Customer ']
train_user_item_matrix = pd.DataFrame(scaler.fit_transform(train_data.iloc[:, 1:]), columns=carpet_attributes, index=train_customers)

test_customers = test_data['Customer ']
test_user_item_matrix = pd.DataFrame(scaler.transform(test_data.iloc[:, 1:]), columns=carpet_attributes, index=test_customers)

In [61]:
# Train the model on the training data
model.fit(train_user_item_matrix, train_user_item_matrix, epochs=num_epochs, verbose=0)

In [62]:
# Make predictions for the test data
test_predictions = model.predict(test_user_item_matrix)

# Compute the MSE between the predicted and actual values
mse = np.mean(np.power(test_predictions - test_user_item_matrix.values, 2))
print(f'Mean squared error: {mse:.4f}')

1/1 [==============================] - 0s 82ms/step
Mean squared error: 29.4950